Calculator UI
brenpardal/Calculator pull request #1
Opened 2020-12-28 13:15 UTC by brenpardal

Implementation of a simple calculator layout design

2020-12-28 13:20 UTC, LuchoElissondoGlobant commented on app/src/main/res/layout/activity_main.xml
> +    android:background="#F8F8F8"
you coulld add this ones in the colors.xml file

2020-12-28 13:23 UTC, mauroLonghi commented on app/src/main/res/layout/activity_main.xml
> +        android:paddingBottom="@dimen/text_padding"
look at the previous textview , some properties are the same so you can use a Style

2020-12-28 13:25 UTC, mauroLonghi commented on app/src/main/res/values/styles.xml
> +    <style name="StyleButtonFirstColour" parent="StyleTextButton">
NICE! very good the use of inheritance

2020-12-28 13:25 UTC, LuchoElissondoGlobant commented on app/src/main/res/values/styles.xml
> +    <style name="StyleButtonFourthColour" parent="StyleTextButton">
just a suggestion, you could give this one the patent of StyleButtonThirdColour and only change the backgroundTint

2020-12-28 13:26 UTC, LuchoElissondoGlobant commented on app/src/main/res/values/styles.xml
> +    <style name="StyleButtonFourthColour" parent="StyleTextButton">
* same suggestion to all the StyleButtonNUMBERcolour

2020-12-28 13:28 UTC, LuchoElissondoGlobant commented on app/src/main/res/values/styles.xml
> +    <style name="StyleButtonFourthColour" parent="StyleTextButton">
or you could move up
<item name="android:textSize">@dimen/button_text_size</item>
 <item name="android:textStyle">bold</item>
 to the current parent

2020-12-28 13:29 UTC, LuchoElissondoGlobant commented on app/src/main/res/values/styles.xml
> +
remove this estra line please

2020-12-28 13:31 UTC, BQuinteros commented
Excellent UI <3

2020-12-28 13:35 UTC, SartiMau requested changes
Pls convert the png images to webp

2020-12-28 13:35 UTC, SartiMau commented on README.md
> +<img src="image_calculator_nexus_s.png"
this is not visible for me

2020-12-28 13:35 UTC, SartiMau commented on app/src/main/java/com/example/calculator/MainActivity.java
> +        setContentView(activity_main);
usually, we show in the code the structure **R.<resource>.<ID>**  to grant legibility. If you use it like this can bring misunderstanding

2020-12-28 13:35 UTC, SartiMau commented on app/src/main/java/com/example/calculator/MainActivity.java
>  }
add empty line at the end to avoid this error

2020-12-28 13:35 UTC, SartiMau commented on app/src/main/res/layout/activity_main.xml
> +    android:background="#F8F8F8"
+1

2020-12-28 13:35 UTC, SartiMau commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/title_app"
you can create a style for all these properties

2020-12-28 13:35 UTC, SartiMau commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/text_operation"
you can create a style for all these properties

2020-12-28 13:35 UTC, SartiMau commented on app/src/main/res/values/strings.xml
> +    <string name="numeric_0">0</string>
do not use numbers in the IDs

2020-12-28 13:35 UTC, SartiMau commented on app/src/main/res/values/styles.xml
> +        <!-- Customize your theme here. -->
as this comment is not necessary, please delete it

2020-12-28 13:35 UTC, SartiMau commented on app/src/main/res/values/styles.xml
> +        <!-- Customize your theme here. -->
same

2020-12-28 13:35 UTC, SartiMau commented on app/src/main/res/values/styles.xml
> +        <!-- Customize your theme here. -->
same

2020-12-28 13:35 UTC, SartiMau commented on app/src/main/res/values/styles.xml
> +        <!-- Customize your theme here. -->
same

2020-12-28 13:35 UTC, SartiMau commented on app/src/main/res/layout/activity_main.xml
>  </androidx.constraintlayout.widget.ConstraintLayout>
add empty line at the end to avoid this error

2020-12-28 13:35 UTC, SartiMau commented on app/src/main/res/values-night/themes.xml
>  </resources>
add empty line at the end to avoid this error

2020-12-28 13:35 UTC, SartiMau commented on app/src/main/res/values/colors.xml
>  </resources>
add empty line at the end to avoid this error

2020-12-28 13:35 UTC, SartiMau commented on app/src/main/res/values/dimens.xml
> +</resources>
add empty line at the end to avoid this error

2020-12-28 13:35 UTC, SartiMau commented on app/src/main/res/values/strings.xml
>  </resources>
add an empty line at the end to avoid this error

2020-12-28 13:35 UTC, SartiMau commented on app/src/main/res/values/styles.xml
> +</resources>
add an empty line at the end to avoid this error

2020-12-28 13:35 UTC, SartiMau commented on app/src/main/res/values/themes.xml
>  </resources>
add an empty line at the end to avoid this error

2020-12-28 14:23 UTC, brenpardal commented on app/src/main/res/values/styles.xml
> +    <style name="StyleButtonFourthColour" parent="StyleTextButton">
Done. Thanks!

2020-12-28 14:28 UTC, brenpardal commented on app/src/main/res/layout/activity_main.xml
> +    android:background="#F8F8F8"
Done

2020-12-28 14:31 UTC, brenpardal commented on app/src/main/res/values/styles.xml
> +    <style name="StyleButtonFirstColour" parent="StyleTextButton">
Thanks!

2020-12-28 14:41 UTC, brenpardal commented on app/src/main/res/layout/activity_main.xml
> +    android:background="#F8F8F8"
Done

2020-12-28 14:56 UTC, brenpardal commented on app/src/main/java/com/example/calculator/MainActivity.java
> +        setContentView(activity_main);
Done

2020-12-28 14:57 UTC, brenpardal commented on app/src/main/java/com/example/calculator/MainActivity.java
>  }
Done

2020-12-28 14:57 UTC, brenpardal commented on app/src/main/res/values/colors.xml
>  </resources>
Done

2020-12-28 15:03 UTC, brenpardal commented on app/src/main/res/layout/activity_main.xml
> +        android:paddingBottom="@dimen/text_padding"
Done =)

2020-12-28 15:07 UTC, brenpardal commented on app/src/main/res/values/styles.xml
> +    <style name="StyleButtonFourthColour" parent="StyleTextButton">
Done. Thanks!

2020-12-28 15:07 UTC, brenpardal commented on app/src/main/res/values/styles.xml
> +
Done

2020-12-28 15:27 UTC, brenpardal commented on app/src/main/res/values/strings.xml
> +    <string name="numeric_0">0</string>
solved

2020-12-28 15:30 UTC, brenpardal commented on app/src/main/res/values/styles.xml
> +        <!-- Customize your theme here. -->
solved

2020-12-28 15:31 UTC, brenpardal commented on app/src/main/res/values/styles.xml
> +        <!-- Customize your theme here. -->
solved

2020-12-28 15:31 UTC, brenpardal commented on app/src/main/res/values/styles.xml
> +        <!-- Customize your theme here. -->
solved

2020-12-28 15:31 UTC, brenpardal commented on app/src/main/res/values/styles.xml
> +        <!-- Customize your theme here. -->
solved

2020-12-28 15:31 UTC, brenpardal commented on app/src/main/res/layout/activity_main.xml
>  </androidx.constraintlayout.widget.ConstraintLayout>
solved

2020-12-28 15:31 UTC, brenpardal commented on app/src/main/res/values-night/themes.xml
>  </resources>
solved

2020-12-28 15:31 UTC, brenpardal commented on app/src/main/res/values/dimens.xml
> +</resources>
solved

2020-12-28 16:01 UTC, brenpardal commented on app/src/main/res/values/styles.xml
> +</resources>
done

2020-12-28 16:04 UTC, brenpardal commented on app/src/main/res/values/themes.xml
>  </resources>
done

2020-12-28 16:22 UTC, brenpardal commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/text_operation"
solved

2020-12-28 16:22 UTC, brenpardal commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/title_app"
solved

2020-12-28 16:24 UTC, brenpardal commented on README.md
> +<img src="image_calculator_nexus_s.png"
Solved. Images removed from readme

2020-12-28 17:26 UTC, mauroLonghi commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/title_app"
I dont see any style here

2020-12-28 17:26 UTC, mauroLonghi commented on app/src/main/res/layout/activity_main.xml
> +        style="@style/StyleButtonSecondColor"
StyleButtonFirstColor & StyleButtonSecondColor it is not a representative name, please, change for another name

2020-12-28 18:35 UTC, brenpardal commented on app/src/main/res/layout/activity_main.xml
> +        style="@style/StyleButtonSecondColor"
solved

2020-12-28 18:53 UTC, mauroLonghi approved these changes

2020-12-28 18:53 UTC, SartiMau requested changes

2020-12-28 18:53 UTC, SartiMau commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginTop="@dimen/text_marginTop"
put this property inside the style

2020-12-28 18:53 UTC, SartiMau commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginStart="@dimen/button_numeric_marginStart"
same

2020-12-28 18:53 UTC, SartiMau commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginTop="@dimen/button_numeric_marginTop"
same

2020-12-28 18:53 UTC, SartiMau commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginStart="@dimen/button_numeric_marginStart"
same

2020-12-28 18:53 UTC, SartiMau commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginTop="@dimen/button_numeric_marginTop"
same

2020-12-28 18:53 UTC, SartiMau commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginStart="@dimen/button_numeric_marginStart"
same here

2020-12-28 18:53 UTC, SartiMau commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginTop="@dimen/button_operator_marginTop"
same here

2020-12-28 18:53 UTC, SartiMau commented on app/src/main/res/values/strings.xml
> +    <string name="hint">Insert operation...</string>
hint is too general, put a more specific name pls 
ie. **insert_operation_hint**

2020-12-28 18:53 UTC, SartiMau commented on app/src/main/res/values/styles.xml
> +    <style name="StyleTextView" parent="TextAppearance.AppCompat.Medium">
StyleTextView is too generic put something more specific..
ie.  **InsertOperationStyle**

2020-12-28 18:53 UTC, SartiMau commented on app/src/main/res/values/styles.xml
> +        <item name="android:layout_height">wrap_content</item>
as a good practice **android:layout_width** and **android:layout_height** should be in the view not in the style

2020-12-29 15:58 UTC, LuchoElissondoGlobant approved these changes

2020-12-29 15:58 UTC, SartiMau approved these changes

2020-12-29 16:01 UTC, BQuinteros approved these changes

2020-12-29 17:07 UTC, mauroLonghi approved these changes

2020-12-29 17:09 UTC, merged